services:
  db:
    image: postgres:16
    container_name: db_app
    volumes:
      - postgresdata:/var/lib/postgresql/data
    env_file:
      - .env

  redis:
    image: redis:7
    container_name: redis_app

  app:
    build:
      context: .
    env_file:
      - .env
    container_name: tasks_app
    command: ["/tasks/docker/app.sh"]
    ports:
      - 8000:8000
    depends_on:
      - db
      - redis

volumes:
  postgresdata:
